# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\"\x1c\n\x0eGetTermRequest\x12\n\n\x02id\x18\x01 \x01(\t\"D\n\x04Term\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\"/\n\x0fGetTermResponse\x12\x1c\n\x04term\x18\x01 \x01(\x0b\x32\x0e.glossary.Term\"D\n\x12SearchTermsRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\"4\n\x13SearchTermsResponse\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term2\x9d\x01\n\x0fGlossaryService\x12>\n\x07GetTerm\x12\x18.glossary.GetTermRequest\x1a\x19.glossary.GetTermResponse\x12J\n\x0bSearchTerms\x12\x1c.glossary.SearchTermsRequest\x1a\x1d.glossary.SearchTermsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTERMREQUEST']._serialized_start=28
  _globals['_GETTERMREQUEST']._serialized_end=56
  _globals['_TERM']._serialized_start=58
  _globals['_TERM']._serialized_end=126
  _globals['_GETTERMRESPONSE']._serialized_start=128
  _globals['_GETTERMRESPONSE']._serialized_end=175
  _globals['_SEARCHTERMSREQUEST']._serialized_start=177
  _globals['_SEARCHTERMSREQUEST']._serialized_end=245
  _globals['_SEARCHTERMSRESPONSE']._serialized_start=247
  _globals['_SEARCHTERMSRESPONSE']._serialized_end=299
  _globals['_GLOSSARYSERVICE']._serialized_start=302
  _globals['_GLOSSARYSERVICE']._serialized_end=459
# @@protoc_insertion_point(module_scope)
